[package]
name = "dct"
version = "0.0.1"
edition = "2021"

[dependencies]
dicom = { version = "0.6.3", default-features = false }
mockd = { version = "0.4.3", features = ["datetime"] }
uuid = { version = "1.6.1", features = ["v4"] }

[dependencies.clap]
version = "4.4.13"
features = ["derive"]
